// مُولَّد من data/glossary.json — لا تعدّله يدوياً (deno task glossary)
export const GLOSSARY = {
  "name": "Manhal Glossary",
  "version": "0.3",
  "date": "2026-10-04",
  "languages": [
    "en",
  ],
  "modes": {
    "transliterate": "يكتب المصطلح بحروف اللغة",
    "translate": "يترجم للمعنى",
    "both": "أول ذكر: المصطلح مع معناه بين قوسين، وبعده المصطلح فقط",
  },
  "fields": {
    "forbidden": "ترجمة خاطئة: الكود يرفضها وينزل الحالة",
    "caution": "ترجمة ممكنة في سياق آخر: الكود ينبه فقط",
  },
  "terms": [
    {
      "id": "allah",
      "ar": "الله",
      "ar_variants": [
        "لله",
        "بالله",
        "والله",
      ],
      "category": "عقيدة",
      "en": {
        "term": "Allah",
        "first_mention": "Allah",
        "mode": "transliterate",
        "forbidden": [],
        "caution": [
          "God",
        ],
      },
      "note": "يُكتب Allah عند الإشارة إلى الله في سياق إسلامي",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "tawhid",
      "ar": "التوحيد",
      "ar_variants": [
        "توحيد",
      ],
      "category": "عقيدة",
      "en": {
        "term": "Tawhid",
        "first_mention": "Tawhid (the Oneness of God: singling out Allah in lordship, worship, and His names and attributes)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "monotheism",
        ],
      },
      "note": "يفضل إبقاء المصطلح مع شرح معناه؛ لا يُختزل في الوحدانية العددية",
      "review_status": "package",
      "source": "الحزمة العلمية للتحدي — نماذج قاموس المصطلحات",
    },
    {
      "id": "shirk",
      "ar": "الشرك",
      "ar_variants": [
        "شرك",
        "الإشراك",
      ],
      "category": "عقيدة",
      "en": {
        "term": "Shirk",
        "first_mention": "Shirk (associating partners with Allah)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "idolatry",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "iman",
      "ar": "الإيمان",
      "ar_variants": [
        "إيمان",
        "الايمان",
      ],
      "category": "عقيدة",
      "en": {
        "term": "Iman",
        "first_mention": "Iman (faith)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "islam",
      "ar": "الإسلام",
      "ar_variants": [
        "اسلام",
        "الاسلام",
      ],
      "category": "عقيدة",
      "en": {
        "term": "Islam",
        "first_mention": "Islam (submission to Allah through Tawhid and obedience)",
        "mode": "transliterate",
        "forbidden": [
          "Mohammedanism",
        ],
        "caution": [],
      },
      "note": "لا يُختزل في معنى ثقافي عام",
      "review_status": "package",
      "source": "الحزمة العلمية للتحدي — نماذج قاموس المصطلحات",
    },
    {
      "id": "ihsan",
      "ar": "الإحسان",
      "ar_variants": [
        "إحسان",
      ],
      "category": "عقيدة",
      "en": {
        "term": "Ihsan",
        "first_mention": "Ihsan (excellence in worship)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "muslim",
      "ar": "مسلم",
      "ar_variants": [
        "المسلم",
        "المسلمون",
        "المسلمين",
      ],
      "category": "عقيدة",
      "en": {
        "term": "Muslim",
        "first_mention": "Muslim",
        "mode": "transliterate",
        "forbidden": [
          "Mohammedan",
          "Moslem",
        ],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "rasul",
      "ar": "الرسول",
      "ar_variants": [
        "رسول",
        "رسول الله",
      ],
      "category": "عقيدة",
      "en": {
        "term": "the Messenger",
        "first_mention": "the Messenger of Allah",
        "mode": "translate",
        "forbidden": [],
        "caution": [
          "apostle",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "nabi",
      "ar": "النبي",
      "ar_variants": [
        "نبي",
        "الأنبياء",
      ],
      "category": "عقيدة",
      "en": {
        "term": "the Prophet",
        "first_mention": "the Prophet",
        "mode": "translate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "salawat",
      "ar": "ﷺ",
      "ar_variants": [
        "صلى الله عليه وسلم",
      ],
      "category": "عقيدة",
      "en": {
        "term": "ﷺ",
        "first_mention": "(peace and blessings be upon him)",
        "mode": "translate",
        "forbidden": [],
        "caution": [],
      },
      "note": "تُكتب بعد اسم النبي",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "wahy",
      "ar": "الوحي",
      "ar_variants": [
        "وحي",
      ],
      "category": "عقيدة",
      "en": {
        "term": "Revelation",
        "first_mention": "Revelation (Wahy)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "inspiration",
        ],
      },
      "note": "ما أوحاه الله إلى أنبيائه؛ تجنب ما يوهم الإلهام الشخصي",
      "review_status": "package",
      "source": "الحزمة العلمية للتحدي — نماذج قاموس المصطلحات",
    },
    {
      "id": "malaika",
      "ar": "الملائكة",
      "ar_variants": [
        "ملائكة",
        "ملك",
        "الملك",
      ],
      "category": "عقيدة",
      "en": {
        "term": "angels",
        "first_mention": "angels",
        "mode": "translate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "jinn",
      "ar": "الجن",
      "ar_variants": [
        "جن",
        "الجان",
      ],
      "category": "عقيدة",
      "en": {
        "term": "Jinn",
        "first_mention": "Jinn",
        "mode": "transliterate",
        "forbidden": [
          "genie",
          "genies",
        ],
        "caution": [
          "demons",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "shaytan",
      "ar": "الشيطان",
      "ar_variants": [
        "شيطان",
        "إبليس",
      ],
      "category": "عقيدة",
      "en": {
        "term": "Satan",
        "first_mention": "Satan (Shaytan)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "إبليس يكتب Iblis",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "akhirah",
      "ar": "الآخرة",
      "ar_variants": [
        "الاخرة",
        "آخرة",
      ],
      "category": "عقيدة",
      "en": {
        "term": "the Hereafter",
        "first_mention": "the Hereafter (al-Akhirah)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "afterlife",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "qiyamah",
      "ar": "يوم القيامة",
      "ar_variants": [
        "القيامة",
      ],
      "category": "عقيدة",
      "en": {
        "term": "the Day of Resurrection",
        "first_mention": "the Day of Resurrection",
        "mode": "translate",
        "forbidden": [],
        "caution": [
          "Doomsday",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "jannah",
      "ar": "الجنة",
      "ar_variants": [
        "جنة",
        "الجنان",
      ],
      "category": "عقيدة",
      "en": {
        "term": "Paradise",
        "first_mention": "Paradise (Jannah)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "heaven",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "nar",
      "ar": "النار",
      "ar_variants": [
        "جهنم",
      ],
      "category": "عقيدة",
      "en": {
        "term": "the Hellfire",
        "first_mention": "the Hellfire (Jahannam)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "qadar",
      "ar": "القدر",
      "ar_variants": [
        "قدر",
        "القضاء والقدر",
      ],
      "category": "عقيدة",
      "en": {
        "term": "Divine Decree",
        "first_mention": "Divine Decree (al-Qadar)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "fate",
          "destiny",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "ghayb",
      "ar": "الغيب",
      "ar_variants": [
        "غيب",
      ],
      "category": "عقيدة",
      "en": {
        "term": "the Unseen",
        "first_mention": "the Unseen (al-Ghayb)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "kufr",
      "ar": "الكفر",
      "ar_variants": [
        "كفر",
      ],
      "category": "عقيدة",
      "en": {
        "term": "disbelief",
        "first_mention": "disbelief (Kufr)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "kafir",
      "ar": "الكافر",
      "ar_variants": [
        "كافر",
        "الكفار",
        "كفار",
      ],
      "category": "عقيدة",
      "en": {
        "term": "disbeliever",
        "first_mention": "disbeliever",
        "mode": "translate",
        "forbidden": [],
        "caution": [
          "infidel",
          "pagan",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "nifaq",
      "ar": "النفاق",
      "ar_variants": [
        "نفاق",
        "المنافقون",
        "المنافقين",
      ],
      "category": "عقيدة",
      "en": {
        "term": "hypocrisy",
        "first_mention": "hypocrisy (Nifaq)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "bidah",
      "ar": "البدعة",
      "ar_variants": [
        "بدعة",
        "البدع",
      ],
      "category": "عقيدة",
      "en": {
        "term": "Bid'ah",
        "first_mention": "Bid'ah (innovation in religion)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "innovation",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "shafaah",
      "ar": "الشفاعة",
      "ar_variants": [
        "شفاعة",
      ],
      "category": "عقيدة",
      "en": {
        "term": "intercession",
        "first_mention": "intercession (Shafa'ah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "asma_husna",
      "ar": "الأسماء الحسنى",
      "ar_variants": [
        "أسماء الله الحسنى",
      ],
      "category": "عقيدة",
      "en": {
        "term": "the Most Beautiful Names of Allah",
        "first_mention": "the Most Beautiful Names of Allah",
        "mode": "translate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "arsh",
      "ar": "العرش",
      "ar_variants": [
        "عرش",
      ],
      "category": "عقيدة",
      "en": {
        "term": "the Throne",
        "first_mention": "the Throne ('Arsh)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "ahl_kitab",
      "ar": "أهل الكتاب",
      "ar_variants": [],
      "category": "عقيدة",
      "en": {
        "term": "the People of the Book",
        "first_mention": "the People of the Book",
        "mode": "translate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "quran",
      "ar": "القرآن",
      "ar_variants": [
        "قرآن",
        "القران",
      ],
      "category": "قرآن وعلومه",
      "en": {
        "term": "the Quran",
        "first_mention": "the Quran",
        "mode": "transliterate",
        "forbidden": [],
        "caution": [
          "Koran",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "surah",
      "ar": "سورة",
      "ar_variants": [
        "السورة",
        "سور",
      ],
      "category": "قرآن وعلومه",
      "en": {
        "term": "Surah",
        "first_mention": "Surah",
        "mode": "transliterate",
        "forbidden": [],
        "caution": [
          "chapter",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "ayah",
      "ar": "آية",
      "ar_variants": [
        "الآية",
        "آيات",
        "اية",
      ],
      "category": "قرآن وعلومه",
      "en": {
        "term": "verse",
        "first_mention": "verse (Ayah)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "sign",
        ],
      },
      "note": "آية بمعنى العلامة تترجم sign حسب السياق",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "tafsir",
      "ar": "التفسير",
      "ar_variants": [
        "تفسير",
      ],
      "category": "قرآن وعلومه",
      "en": {
        "term": "Tafsir",
        "first_mention": "Tafsir (exegesis of the Quran)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "tilawah",
      "ar": "التلاوة",
      "ar_variants": [
        "تلاوة",
      ],
      "category": "قرآن وعلومه",
      "en": {
        "term": "recitation",
        "first_mention": "recitation (Tilawah)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "reading",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "tajwid",
      "ar": "التجويد",
      "ar_variants": [
        "تجويد",
      ],
      "category": "قرآن وعلومه",
      "en": {
        "term": "Tajwid",
        "first_mention": "Tajwid (rules of Quranic recitation)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "mushaf",
      "ar": "المصحف",
      "ar_variants": [
        "مصحف",
      ],
      "category": "قرآن وعلومه",
      "en": {
        "term": "Mushaf",
        "first_mention": "Mushaf (written copy of the Quran)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "juz",
      "ar": "جزء",
      "ar_variants": [
        "الجزء",
        "أجزاء",
      ],
      "category": "قرآن وعلومه",
      "en": {
        "term": "Juz'",
        "first_mention": "Juz' (one of thirty parts of the Quran)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "hafiz",
      "ar": "حافظ",
      "ar_variants": [
        "الحافظ",
        "حفظة",
      ],
      "category": "قرآن وعلومه",
      "en": {
        "term": "Hafiz",
        "first_mention": "Hafiz (one who has memorized the Quran)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "hadith",
      "ar": "حديث",
      "ar_variants": [
        "الحديث",
        "أحاديث",
        "الأحاديث",
      ],
      "category": "حديث وعلومه",
      "en": {
        "term": "Hadith",
        "first_mention": "Hadith (what is reported from the Prophet ﷺ of his words, actions or approvals)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "tradition",
        ],
      },
      "note": "مع بيان درجة الثبوت عند الاستدلال",
      "review_status": "package",
      "source": "الحزمة العلمية للتحدي — نماذج قاموس المصطلحات",
    },
    {
      "id": "sunnah",
      "ar": "السنة",
      "ar_variants": [
        "سنة",
        "السنة النبوية",
      ],
      "category": "حديث وعلومه",
      "en": {
        "term": "the Sunnah",
        "first_mention": "the Sunnah (the Prophet's guidance and way)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "يحدد المقصود بحسب السياق العلمي",
      "review_status": "package",
      "source": "الحزمة العلمية للتحدي — نماذج قاموس المصطلحات",
    },
    {
      "id": "sahih",
      "ar": "صحيح",
      "ar_variants": [
        "الصحيح",
      ],
      "category": "حديث وعلومه",
      "en": {
        "term": "Sahih",
        "first_mention": "Sahih (authentic)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "correct",
        ],
      },
      "note": "في سياق الحكم على الحديث",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "hasan",
      "ar": "حسن",
      "ar_variants": [],
      "category": "حديث وعلومه",
      "en": {
        "term": "Hasan",
        "first_mention": "Hasan (sound)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "good",
          "good-looking",
        ],
      },
      "note": "في سياق الحكم على الحديث",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "daif",
      "ar": "ضعيف",
      "ar_variants": [
        "الضعيف",
      ],
      "category": "حديث وعلومه",
      "en": {
        "term": "Da'if",
        "first_mention": "Da'if (weak)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "mawdu",
      "ar": "موضوع",
      "ar_variants": [
        "الموضوع",
        "موضوعة",
      ],
      "category": "حديث وعلومه",
      "en": {
        "term": "Mawdu'",
        "first_mention": "Mawdu' (fabricated)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "subject",
          "topic",
        ],
      },
      "note": "في سياق الحكم على الحديث فقط",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "isnad",
      "ar": "الإسناد",
      "ar_variants": [
        "إسناد",
        "السند",
        "سند",
      ],
      "category": "حديث وعلومه",
      "en": {
        "term": "Isnad",
        "first_mention": "Isnad (chain of narration)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "matn",
      "ar": "المتن",
      "ar_variants": [
        "متن",
      ],
      "category": "حديث وعلومه",
      "en": {
        "term": "Matn",
        "first_mention": "Matn (text of the narration)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "sahabah",
      "ar": "الصحابة",
      "ar_variants": [
        "صحابي",
        "الصحابي",
        "الصحابة الكرام",
      ],
      "category": "حديث وعلومه",
      "en": {
        "term": "the Companions",
        "first_mention": "the Companions (Sahabah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "tabiun",
      "ar": "التابعون",
      "ar_variants": [
        "التابعين",
        "تابعي",
      ],
      "category": "حديث وعلومه",
      "en": {
        "term": "the Successors",
        "first_mention": "the Successors (Tabi'un)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "athar",
      "ar": "أثر",
      "ar_variants": [
        "الأثر",
        "آثار",
      ],
      "category": "حديث وعلومه",
      "en": {
        "term": "Athar",
        "first_mention": "Athar (narration from the Companions)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "muttafaq",
      "ar": "متفق عليه",
      "ar_variants": [],
      "category": "حديث وعلومه",
      "en": {
        "term": "agreed upon",
        "first_mention": "agreed upon (by al-Bukhari and Muslim)",
        "mode": "translate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "sirah",
      "ar": "السيرة",
      "ar_variants": [
        "السيرة النبوية",
        "سيرة",
      ],
      "category": "حديث وعلومه",
      "en": {
        "term": "Sirah",
        "first_mention": "Sirah (the Prophet's biography)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "taharah",
      "ar": "الطهارة",
      "ar_variants": [
        "طهارة",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "purification",
        "first_mention": "purification (Taharah)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "cleanliness",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "wudu",
      "ar": "الوضوء",
      "ar_variants": [
        "وضوء",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Wudu'",
        "first_mention": "Wudu' (ablution)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "ghusl",
      "ar": "الغسل",
      "ar_variants": [
        "غسل",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Ghusl",
        "first_mention": "Ghusl (ritual bath)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "shower",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "tayammum",
      "ar": "التيمم",
      "ar_variants": [
        "تيمم",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Tayammum",
        "first_mention": "Tayammum (dry ablution)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "salah",
      "ar": "الصلاة",
      "ar_variants": [
        "صلاة",
        "الصلوات",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Salah",
        "first_mention": "Salah (ritual prayer)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "prayer",
        ],
      },
      "note": "prayer وحدها تختلط بالدعاء",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "dua",
      "ar": "الدعاء",
      "ar_variants": [
        "دعاء",
        "أدعية",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "supplication",
        "first_mention": "supplication (Du'a)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "prayer",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "adhan",
      "ar": "الأذان",
      "ar_variants": [
        "أذان",
        "الاذان",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Adhan",
        "first_mention": "Adhan (call to prayer)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "iqamah",
      "ar": "الإقامة",
      "ar_variants": [
        "إقامة",
        "الاقامة",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Iqamah",
        "first_mention": "Iqamah (second call to prayer)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "residence",
        ],
      },
      "note": "في سياق الصلاة",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "qiblah",
      "ar": "القبلة",
      "ar_variants": [
        "قبلة",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Qiblah",
        "first_mention": "Qiblah (direction of prayer)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "rakah",
      "ar": "ركعة",
      "ar_variants": [
        "الركعة",
        "ركعات",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Rak'ah",
        "first_mention": "Rak'ah (unit of prayer)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "ruku",
      "ar": "الركوع",
      "ar_variants": [
        "ركوع",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "bowing",
        "first_mention": "bowing (Ruku')",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "sujud",
      "ar": "السجود",
      "ar_variants": [
        "سجود",
        "سجدة",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "prostration",
        "first_mention": "prostration (Sujud)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "tashahhud",
      "ar": "التشهد",
      "ar_variants": [
        "تشهد",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Tashahhud",
        "first_mention": "Tashahhud (testimony recited in prayer)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "imam",
      "ar": "الإمام",
      "ar_variants": [
        "إمام",
        "الامام",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Imam",
        "first_mention": "Imam (prayer leader)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "masjid",
      "ar": "المسجد",
      "ar_variants": [
        "مسجد",
        "المساجد",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "mosque",
        "first_mention": "mosque",
        "mode": "translate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "jumuah",
      "ar": "صلاة الجمعة",
      "ar_variants": [
        "الجمعة",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Jumu'ah",
        "first_mention": "Jumu'ah (Friday prayer)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "khutbah",
      "ar": "الخطبة",
      "ar_variants": [
        "خطبة",
        "خطبة الجمعة",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Khutbah",
        "first_mention": "Khutbah (sermon)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "speech",
          "lecture",
        ],
      },
      "note": "خِطبة بكسر الخاء (طلب الزواج) تترجم proposal",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "khatib",
      "ar": "الخطيب",
      "ar_variants": [
        "خطيب",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Khatib",
        "first_mention": "Khatib (preacher)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "jamaah",
      "ar": "صلاة الجماعة",
      "ar_variants": [
        "الجماعة",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "congregational prayer",
        "first_mention": "congregational prayer",
        "mode": "translate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "nafl",
      "ar": "النافلة",
      "ar_variants": [
        "نافلة",
        "النوافل",
        "التطوع",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "voluntary prayer",
        "first_mention": "voluntary prayer (Nafl)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "witr",
      "ar": "الوتر",
      "ar_variants": [
        "وتر",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Witr",
        "first_mention": "Witr (odd-numbered night prayer)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "tarawih",
      "ar": "التراويح",
      "ar_variants": [
        "صلاة التراويح",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Tarawih",
        "first_mention": "Tarawih (night prayers in Ramadan)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "dhikr",
      "ar": "الذكر",
      "ar_variants": [
        "ذكر",
        "الأذكار",
        "أذكار",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Dhikr",
        "first_mention": "Dhikr (remembrance of Allah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "tasbih",
      "ar": "التسبيح",
      "ar_variants": [
        "تسبيح",
        "سبحان الله",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Tasbih",
        "first_mention": "Tasbih (glorifying Allah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "istighfar",
      "ar": "الاستغفار",
      "ar_variants": [
        "استغفار",
      ],
      "category": "طهارة وصلاة",
      "en": {
        "term": "Istighfar",
        "first_mention": "Istighfar (seeking Allah's forgiveness)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "zakah",
      "ar": "الزكاة",
      "ar_variants": [
        "زكاة",
      ],
      "category": "زكاة وصدقة",
      "en": {
        "term": "Zakah",
        "first_mention": "Zakah (obligatory alms)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "charity",
          "tax",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "sadaqah",
      "ar": "الصدقة",
      "ar_variants": [
        "صدقة",
        "الصدقات",
      ],
      "category": "زكاة وصدقة",
      "en": {
        "term": "Sadaqah",
        "first_mention": "Sadaqah (voluntary charity)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "zakat_fitr",
      "ar": "زكاة الفطر",
      "ar_variants": [],
      "category": "زكاة وصدقة",
      "en": {
        "term": "Zakat al-Fitr",
        "first_mention": "Zakat al-Fitr (end-of-Ramadan alms)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "nisab",
      "ar": "النصاب",
      "ar_variants": [
        "نصاب",
      ],
      "category": "زكاة وصدقة",
      "en": {
        "term": "Nisab",
        "first_mention": "Nisab (minimum threshold for Zakah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "waqf",
      "ar": "الوقف",
      "ar_variants": [
        "وقف",
        "الأوقاف",
      ],
      "category": "زكاة وصدقة",
      "en": {
        "term": "Waqf",
        "first_mention": "Waqf (charitable endowment)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "sawm",
      "ar": "الصيام",
      "ar_variants": [
        "صيام",
        "الصوم",
        "صوم",
      ],
      "category": "صيام",
      "en": {
        "term": "fasting",
        "first_mention": "fasting (Sawm)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "ramadan",
      "ar": "رمضان",
      "ar_variants": [
        "شهر رمضان",
      ],
      "category": "صيام",
      "en": {
        "term": "Ramadan",
        "first_mention": "Ramadan",
        "mode": "transliterate",
        "forbidden": [
          "Ramadan holiday",
        ],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "suhur",
      "ar": "السحور",
      "ar_variants": [
        "سحور",
      ],
      "category": "صيام",
      "en": {
        "term": "Suhur",
        "first_mention": "Suhur (pre-dawn meal)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "iftar",
      "ar": "الإفطار",
      "ar_variants": [
        "إفطار",
        "الفطور",
      ],
      "category": "صيام",
      "en": {
        "term": "Iftar",
        "first_mention": "Iftar (meal to break the fast)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "itikaf",
      "ar": "الاعتكاف",
      "ar_variants": [
        "اعتكاف",
      ],
      "category": "صيام",
      "en": {
        "term": "I'tikaf",
        "first_mention": "I'tikaf (spiritual retreat in the mosque)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "laylat_qadr",
      "ar": "ليلة القدر",
      "ar_variants": [],
      "category": "صيام",
      "en": {
        "term": "Laylat al-Qadr",
        "first_mention": "Laylat al-Qadr (the Night of Decree)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "eid_fitr",
      "ar": "عيد الفطر",
      "ar_variants": [],
      "category": "صيام",
      "en": {
        "term": "Eid al-Fitr",
        "first_mention": "Eid al-Fitr",
        "mode": "transliterate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "hajj",
      "ar": "الحج",
      "ar_variants": [
        "حج",
      ],
      "category": "حج وعمرة",
      "en": {
        "term": "Hajj",
        "first_mention": "Hajj (pilgrimage to Makkah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "umrah",
      "ar": "العمرة",
      "ar_variants": [
        "عمرة",
      ],
      "category": "حج وعمرة",
      "en": {
        "term": "Umrah",
        "first_mention": "Umrah (lesser pilgrimage)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "ihram",
      "ar": "الإحرام",
      "ar_variants": [
        "إحرام",
        "محرم",
      ],
      "category": "حج وعمرة",
      "en": {
        "term": "Ihram",
        "first_mention": "Ihram (state of ritual consecration)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "miqat",
      "ar": "الميقات",
      "ar_variants": [
        "ميقات",
        "المواقيت",
      ],
      "category": "حج وعمرة",
      "en": {
        "term": "Miqat",
        "first_mention": "Miqat (station for entering Ihram)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "tawaf",
      "ar": "الطواف",
      "ar_variants": [
        "طواف",
      ],
      "category": "حج وعمرة",
      "en": {
        "term": "Tawaf",
        "first_mention": "Tawaf (circumambulation of the Ka'bah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "sai",
      "ar": "السعي",
      "ar_variants": [
        "سعي",
      ],
      "category": "حج وعمرة",
      "en": {
        "term": "Sa'i",
        "first_mention": "Sa'i (walking between Safa and Marwah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "kabah",
      "ar": "الكعبة",
      "ar_variants": [
        "كعبة",
        "البيت الحرام",
      ],
      "category": "حج وعمرة",
      "en": {
        "term": "the Ka'bah",
        "first_mention": "the Ka'bah",
        "mode": "transliterate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "masjid_haram",
      "ar": "المسجد الحرام",
      "ar_variants": [
        "الحرم",
      ],
      "category": "حج وعمرة",
      "en": {
        "term": "al-Masjid al-Haram",
        "first_mention": "al-Masjid al-Haram (the Sacred Mosque)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "makkah",
      "ar": "مكة",
      "ar_variants": [
        "مكة المكرمة",
      ],
      "category": "حج وعمرة",
      "en": {
        "term": "Makkah",
        "first_mention": "Makkah",
        "mode": "transliterate",
        "forbidden": [],
        "caution": [
          "Mecca",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "madinah",
      "ar": "المدينة",
      "ar_variants": [
        "المدينة المنورة",
      ],
      "category": "حج وعمرة",
      "en": {
        "term": "Madinah",
        "first_mention": "Madinah",
        "mode": "transliterate",
        "forbidden": [],
        "caution": [
          "Medina",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "arafah",
      "ar": "عرفة",
      "ar_variants": [
        "عرفات",
        "يوم عرفة",
      ],
      "category": "حج وعمرة",
      "en": {
        "term": "'Arafah",
        "first_mention": "'Arafah",
        "mode": "transliterate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "muzdalifah",
      "ar": "مزدلفة",
      "ar_variants": [],
      "category": "حج وعمرة",
      "en": {
        "term": "Muzdalifah",
        "first_mention": "Muzdalifah",
        "mode": "transliterate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "mina",
      "ar": "منى",
      "ar_variants": [],
      "category": "حج وعمرة",
      "en": {
        "term": "Mina",
        "first_mention": "Mina",
        "mode": "transliterate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "jamarat",
      "ar": "رمي الجمرات",
      "ar_variants": [
        "الجمرات",
        "الجمرة",
      ],
      "category": "حج وعمرة",
      "en": {
        "term": "stoning of the Jamarat",
        "first_mention": "stoning of the Jamarat",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "stoning the devil",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "talbiyah",
      "ar": "التلبية",
      "ar_variants": [
        "تلبية",
      ],
      "category": "حج وعمرة",
      "en": {
        "term": "Talbiyah",
        "first_mention": "Talbiyah (the pilgrim's chant)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "hady",
      "ar": "الهدي",
      "ar_variants": [
        "هدي",
      ],
      "category": "حج وعمرة",
      "en": {
        "term": "Hady",
        "first_mention": "Hady (sacrificial animal of Hajj)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "udhiyah",
      "ar": "الأضحية",
      "ar_variants": [
        "أضحية",
        "الأضاحي",
      ],
      "category": "حج وعمرة",
      "en": {
        "term": "Udhiyah",
        "first_mention": "Udhiyah (Eid sacrifice)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "eid_adha",
      "ar": "عيد الأضحى",
      "ar_variants": [],
      "category": "حج وعمرة",
      "en": {
        "term": "Eid al-Adha",
        "first_mention": "Eid al-Adha",
        "mode": "transliterate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "shariah",
      "ar": "الشريعة",
      "ar_variants": [
        "شريعة",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "Shari'ah",
        "first_mention": "Shari'ah (Islamic law and guidance)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "Sharia law",
          "penal code",
        ],
      },
      "note": "لا يُختزل في العقوبات أو القانون الجنائي",
      "review_status": "package",
      "source": "الحزمة العلمية للتحدي — نماذج قاموس المصطلحات",
    },
    {
      "id": "fiqh",
      "ar": "الفقه",
      "ar_variants": [
        "فقه",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "Fiqh",
        "first_mention": "Fiqh (Islamic jurisprudence)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "fatwa",
      "ar": "الفتوى",
      "ar_variants": [
        "فتوى",
        "فتاوى",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "Fatwa",
        "first_mention": "Fatwa (a religious ruling issued by a qualified scholar)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "edict",
          "decree",
        ],
      },
      "note": "جواب شرعي يصدره مؤهل؛ لا يساوى بالمعلومة العامة",
      "review_status": "package",
      "source": "الحزمة العلمية للتحدي — نماذج قاموس المصطلحات",
    },
    {
      "id": "mufti",
      "ar": "المفتي",
      "ar_variants": [
        "مفتي",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "Mufti",
        "first_mention": "Mufti (scholar authorized to issue Fatwas)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "halal",
      "ar": "الحلال",
      "ar_variants": [
        "حلال",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "Halal",
        "first_mention": "Halal (permissible)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "haram",
      "ar": "الحرام",
      "ar_variants": [
        "حرام",
        "محرم",
        "محرمة",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "Haram",
        "first_mention": "Haram (prohibited)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "makruh",
      "ar": "المكروه",
      "ar_variants": [
        "مكروه",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "Makruh",
        "first_mention": "Makruh (disliked)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "hated",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "mustahabb",
      "ar": "المستحب",
      "ar_variants": [
        "مستحب",
        "المندوب",
        "مندوب",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "recommended",
        "first_mention": "recommended (Mustahabb)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "mubah",
      "ar": "المباح",
      "ar_variants": [
        "مباح",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "permissible",
        "first_mention": "permissible (Mubah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "wajib",
      "ar": "الواجب",
      "ar_variants": [
        "واجب",
        "الفرض",
        "فرض",
        "فريضة",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "obligatory",
        "first_mention": "obligatory (Fard)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "ijma",
      "ar": "الإجماع",
      "ar_variants": [
        "إجماع",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "consensus",
        "first_mention": "consensus (Ijma')",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "qiyas",
      "ar": "القياس",
      "ar_variants": [
        "قياس",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "analogy",
        "first_mention": "analogical reasoning (Qiyas)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "measurement",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "ijtihad",
      "ar": "الاجتهاد",
      "ar_variants": [
        "اجتهاد",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "Ijtihad",
        "first_mention": "Ijtihad (independent juristic reasoning)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "madhhab",
      "ar": "المذهب",
      "ar_variants": [
        "مذهب",
        "المذاهب",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "Madhhab",
        "first_mention": "Madhhab (school of jurisprudence)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "sect",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "awrah",
      "ar": "العورة",
      "ar_variants": [
        "عورة",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "'Awrah",
        "first_mention": "'Awrah (parts of the body to be covered)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "hijab",
      "ar": "الحجاب",
      "ar_variants": [
        "حجاب",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "Hijab",
        "first_mention": "Hijab",
        "mode": "transliterate",
        "forbidden": [],
        "caution": [
          "veil",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "riba",
      "ar": "الربا",
      "ar_variants": [
        "ربا",
      ],
      "category": "فقه وأصوله",
      "en": {
        "term": "Riba",
        "first_mention": "Riba (usury/interest)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "nikah",
      "ar": "النكاح",
      "ar_variants": [
        "نكاح",
        "عقد النكاح",
      ],
      "category": "أسرة ومعاملات",
      "en": {
        "term": "marriage",
        "first_mention": "marriage contract (Nikah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "mahr",
      "ar": "المهر",
      "ar_variants": [
        "مهر",
        "الصداق",
      ],
      "category": "أسرة ومعاملات",
      "en": {
        "term": "Mahr",
        "first_mention": "Mahr (bridal gift from the groom to the bride)",
        "mode": "both",
        "forbidden": [
          "dowry",
        ],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "talaq",
      "ar": "الطلاق",
      "ar_variants": [
        "طلاق",
      ],
      "category": "أسرة ومعاملات",
      "en": {
        "term": "divorce",
        "first_mention": "divorce (Talaq)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "iddah",
      "ar": "العدة",
      "ar_variants": [
        "عدة",
      ],
      "category": "أسرة ومعاملات",
      "en": {
        "term": "'Iddah",
        "first_mention": "'Iddah (waiting period)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "mirath",
      "ar": "الميراث",
      "ar_variants": [
        "ميراث",
        "المواريث",
        "الإرث",
      ],
      "category": "أسرة ومعاملات",
      "en": {
        "term": "inheritance",
        "first_mention": "inheritance",
        "mode": "translate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "silat_rahim",
      "ar": "صلة الرحم",
      "ar_variants": [],
      "category": "أسرة ومعاملات",
      "en": {
        "term": "maintaining kinship ties",
        "first_mention": "maintaining kinship ties",
        "mode": "translate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "birr_walidayn",
      "ar": "بر الوالدين",
      "ar_variants": [],
      "category": "أسرة ومعاملات",
      "en": {
        "term": "dutifulness to parents",
        "first_mention": "dutifulness to parents",
        "mode": "translate",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "taqwa",
      "ar": "التقوى",
      "ar_variants": [
        "تقوى",
      ],
      "category": "أخلاق وعبارات",
      "en": {
        "term": "Taqwa",
        "first_mention": "Taqwa (mindfulness of Allah)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "fear",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "jihad",
      "ar": "الجهاد",
      "ar_variants": [
        "جهاد",
      ],
      "category": "أخلاق وعبارات",
      "en": {
        "term": "Jihad",
        "first_mention": "Jihad (striving in the cause of Allah)",
        "mode": "both",
        "forbidden": [
          "holy war",
        ],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "hijrah",
      "ar": "الهجرة",
      "ar_variants": [
        "هجرة",
      ],
      "category": "أخلاق وعبارات",
      "en": {
        "term": "Hijrah",
        "first_mention": "Hijrah (the Prophet's migration to Madinah)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "flight",
        ],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "dawah",
      "ar": "الدعوة",
      "ar_variants": [
        "دعوة",
      ],
      "category": "أخلاق وعبارات",
      "en": {
        "term": "Da'wah",
        "first_mention": "Da'wah (invitation to Islam)",
        "mode": "both",
        "forbidden": [],
        "caution": [
          "proselytizing",
        ],
      },
      "note": "يختار المقابل بحسب السياق والجمهور",
      "review_status": "package",
      "source": "الحزمة العلمية للتحدي — نماذج قاموس المصطلحات",
    },
    {
      "id": "ummah",
      "ar": "الأمة",
      "ar_variants": [
        "أمة",
        "الأمة الإسلامية",
      ],
      "category": "أخلاق وعبارات",
      "en": {
        "term": "the Ummah",
        "first_mention": "the Ummah (the Muslim community)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "tawbah",
      "ar": "التوبة",
      "ar_variants": [
        "توبة",
      ],
      "category": "أخلاق وعبارات",
      "en": {
        "term": "repentance",
        "first_mention": "repentance (Tawbah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "niyyah",
      "ar": "النية",
      "ar_variants": [
        "نية",
      ],
      "category": "أخلاق وعبارات",
      "en": {
        "term": "intention",
        "first_mention": "intention (Niyyah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "sabr",
      "ar": "الصبر",
      "ar_variants": [
        "صبر",
      ],
      "category": "أخلاق وعبارات",
      "en": {
        "term": "patience",
        "first_mention": "patience (Sabr)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "tawakkul",
      "ar": "التوكل",
      "ar_variants": [
        "توكل",
      ],
      "category": "أخلاق وعبارات",
      "en": {
        "term": "reliance on Allah",
        "first_mention": "reliance on Allah (Tawakkul)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "ghibah",
      "ar": "الغيبة",
      "ar_variants": [
        "غيبة",
      ],
      "category": "أخلاق وعبارات",
      "en": {
        "term": "backbiting",
        "first_mention": "backbiting (Ghibah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "bismillah",
      "ar": "بسم الله",
      "ar_variants": [
        "بسم الله الرحمن الرحيم",
      ],
      "category": "أخلاق وعبارات",
      "en": {
        "term": "Bismillah",
        "first_mention": "In the name of Allah (Bismillah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "inshallah",
      "ar": "إن شاء الله",
      "ar_variants": [
        "ان شاء الله",
      ],
      "category": "أخلاق وعبارات",
      "en": {
        "term": "In sha' Allah",
        "first_mention": "In sha' Allah (if Allah wills)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "alhamdulillah",
      "ar": "الحمد لله",
      "ar_variants": [
        "الحمدلله",
      ],
      "category": "أخلاق وعبارات",
      "en": {
        "term": "Alhamdulillah",
        "first_mention": "Alhamdulillah (all praise is due to Allah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "salam",
      "ar": "السلام عليكم",
      "ar_variants": [
        "السلام عليكم ورحمة الله",
      ],
      "category": "أخلاق وعبارات",
      "en": {
        "term": "Assalamu 'alaykum",
        "first_mention": "Assalamu 'alaykum (peace be upon you)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "",
      "review_status": "draft",
      "source": "مسودة منهل — تُطابق مع موسوعة المصطلحات الإسلامية terminologyenc.com وموسوعة الجمهرة",
    },
    {
      "id": "ibadah",
      "ar": "العبادة",
      "ar_variants": [
        "عبادة",
        "العبادات",
      ],
      "category": "عقيدة",
      "en": {
        "term": "worship",
        "first_mention": "worship ('Ibadah)",
        "mode": "both",
        "forbidden": [],
        "caution": [],
      },
      "note": "تشمل أعمال القلب والقول والعمل؛ لا تحصر في الشعائر",
      "review_status": "package",
      "source": "الحزمة العلمية للتحدي — نماذج قاموس المصطلحات",
    },
    {
      "id": "nubuwwah",
      "ar": "النبوة",
      "ar_variants": [
        "نبوة",
      ],
      "category": "عقيدة",
      "en": {
        "term": "Prophethood",
        "first_mention": "Prophethood",
        "mode": "translate",
        "forbidden": [],
        "caution": [],
      },
      "note": "اصطفاء الأنبياء بالوحي؛ تمييزها عن القيادة الدينية البشرية",
      "review_status": "package",
      "source": "الحزمة العلمية للتحدي — نماذج قاموس المصطلحات",
    },
  ],
  "reference":
    "موسوعة الجمهرة islamic-content.com/dictionary وموسوعة المصطلحات الإسلامية terminologyenc.com (الحزمة العلمية للتحدي)",
} as const;
